/**
 * Navigation type definitions for Expo Router.
 * Typed routes are generated by Expo Router via "typedRoutes" experiment.
 * These interfaces supplement the generated types with domain-specific params.
 */

export type AuthRoutes = {
  '/(auth)/login': undefined;
  '/(auth)/onboarding': undefined;
  '/(auth)/verify': { phone: string };
};

export type MainTabRoutes = {
  '/(main)/(tabs)/home': undefined;
  '/(main)/(tabs)/ai': undefined;
  '/(main)/(tabs)/orders': undefined;
  '/(main)/(tabs)/flat': undefined;
  '/(main)/(tabs)/profile': undefined;
};

export type ModalRoutes = {
  '/(main)/order-detail': { orderId: string };
  '/(main)/restaurant-detail': { restaurantId: string };
  '/(main)/poll-detail': { pollId: string };
  '/(main)/member-profile': { memberId: string };
  '/(main)/payment-detail': { orderId: string };
  '/(main)/invite-member': undefined;
  '/(main)/settings': undefined;
};

export type AppRoutes = AuthRoutes & MainTabRoutes & ModalRoutes;

// Deep link paths (roomieai://)
export type DeepLinkPath =
  | '/join' // join flat via invite code
  | '/order' // specific order
  | '/poll' // specific poll
  | '/payment'; // payment detail
